version: '3'

services:
  spring-boot:
    build: ./spring-server/fx_bank
    ports:
      - "7968:8080"
    volumes:
      - /home/kim2sin/application.properties:/config/application.properties
      - /home/kim2sin/Wallet_ATQGGWDFRRT7KEMU:/wallet
    restart: always

  fastapi-agent:
    build: ./fastapi-agent
    container_name: fastapi-agent
    ports:
      - "7962:8000"
    env_file:
      - ./fastapi-agent/.env
    volumes:
      - /home/kim2sin/Wallet_ATQGGWDFRRT7KEMU:/wallet
    restart: always

  fastapi-bnk:
    build: ./fastapi-bnk
    container_name: fastapi-bnk
    ports:
      - "7961:8001"
    restart: always

  fastapi-ocr:
    build: ./fastapi-ocr
    container_name: fastapi-ocr
    ports:
      - "7963:8003"
    env_file:
      - ./fastapi-ocr/.env
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "7960:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - spring-boot
      - fastapi-agent
      - fastapi-bnk
      - fastapi-ocr
    restart: always

  redis:
    image: redis:alpine
    container_name: fx_bank-redis
    ports:
      - "6379:6379"
    restart: always